#171 RecordContainer のレビュー修正
Let-s-Hack/goggl pull request #191
Opened 2020-01-22 23:09 UTC by KeisukeHomma

2020-01-23 14:54 UTC, usmysa requested changes
コメントの追加

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +        :recordGroup="recordGroup"
propsはケバブケースだよね...
https://jp.vuejs.org/v2/style-guide/index.html#%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%E5%90%8D%E3%81%AE%E5%9E%8B%E5%BC%8F-%E5%BC%B7%E3%81%8F%E6%8E%A8%E5%A5%A8

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +import moment from 'moment';
lodash → moment → vue-property-decorator
アルファベット順

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +  private get recordGroups(): IRecordGroup[] {
recordGroupsっていうcomputedで、nextRecordGroupsっていう変数がreturnされてる
つまり、recordGroups = nextRecordGroups。
そして、nextRecordGroupsの初期値はthis.recordManger.recordState
まとめると、recordGroups = nextRecordGroups = this.recordManger.recordStateっていう条件が成り立つ。
（A = B、B = Cならば、A = B = Cと同じ理論）
変数名と関係性が意味不明。

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +  private static groupByDate(recordGroups: ITimerState[]): IRecordGroup[] {
この関数の引数のrecordGroupsの型は、ITimerState[]
computedのrecordGroupsの型は、IRecordGroup[]
同じ変数名で型が違う...

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +      const date: string = moment(value.startDatetime!).format('YYYY-MM-DD');
> value.startDatetime

valueっていう変数名は、おかしい
そもそもstartDatetimeも値だから、値の`startDatetime`って意味不明

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +      const targetIndex: number = result.findIndex((recordGroup: IRecordGroup) => (
個人的には、抽象的な変数で微妙...
すごい具体的な処理でわかりやすい関数で使うなら良いんだけど、reduceっていうよく分からない関数の中で使ってるから分かりづらい...
（実際問題、自分でコメントを書いているっていうことは、自分でも分かりづらいからコメントを残してる証拠）

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +    nextRecordGroups = RecordContainer.groupByDate(nextRecordGroups);
SQL的な考えをすると、groupByしてからorderByかな
orderByの処理が複雑になるなら、今のままでいいけど
https://qiita.com/suzukito/items/edcd00e680186f2930a8

2020-01-23 14:54 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +    return reduce(recordGroups, (
2、3行の処理でreduceを使うのは分かるけど、こんなロジックが多い関数でreduceを使う目的は何のだろうか

2020-01-25 02:29 UTC, KeisukeHomma reviewed
コメント追加

2020-01-25 02:29 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +    nextRecordGroups = RecordContainer.groupByDate(nextRecordGroups);
💡

2020-01-25 02:29 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +  private static groupByDate(recordGroups: ITimerState[]): IRecordGroup[] {
確かに気持ち悪いな・・・直します

2020-01-25 02:29 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +    return reduce(recordGroups, (
forEachにした。
reduce って、どういう場合に適しているのだろうか？

2020-01-25 02:29 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +      const prevIndex = recordGroups.length - 1;
prevIndex が 何を指しているのか分かりにくい？

2020-01-25 04:44 UTC, usmysa reviewed
コメントの追加

2020-01-25 04:44 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +      if (typeof record.startDatetime !== 'string') return;
startDatetimeが文字列じゃないケースってどんな時だっけ？

2020-01-25 04:44 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +    return recordGroups;
```
[
  { date: "2020-01-20", records: Array },
  { date: "2020-01-19", records: Array },
  { date: "2020-01-18", records: Array },
]
```
っていうデータ構造なんだけど、そもそも下のデータ構造ではダメなんだっけ？
```
{
  "2020-01-20": Array,
  "2020-01-19": Array,
  "2020-01-18": Array,
}
```

2020-01-25 05:23 UTC, KeisukeHomma reviewed
コメント追加

2020-01-25 05:23 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +    return recordGroups;
並び順を担保するため

2020-01-25 05:23 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +      if (record.startDatetime === null) return;
`record.startDatetime` がnullの場合を考慮しろって怒られるから、nullを弾いている

2020-01-25 10:47 UTC, usmysa reviewed
コメントの追加

2020-01-25 10:47 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +      const equalDateIndex: number = findLastIndex(recordGroups, { date });
> equal: 複数の物の大きさや量、程度などが「等しい」ことを表す。

どちらかというと、sameかな

2020-01-25 10:47 UTC, usmysa commented on src/components/organisms/RecordContainer.vue
> +    return recordGroups;
ちなみに、propsで値を渡す時に並び順が変わるのは知ってるけど、v-forで渡したときにも並び順がソートされるの？

2020-01-25 13:04 UTC, KeisukeHomma reviewed
コメント

2020-01-25 13:04 UTC, KeisukeHomma commented on src/components/organisms/RecordContainer.vue
> +    return recordGroups;
オブジェクトの並び順の話？
Chromeでは、基本的に数値だったら数値順、文字列だったら挿入順になるみたい。

> Objectの順序（chrome）
1. 数値順
2. 挿入順

https://qiita.com/suguru03/items/bf48610225fefcb0f45e

ちなみに、試してみたけどpropsで渡してもforで回してもオブジェクトの並び順は変わらなかった。。

2020-01-25 13:30 UTC, merged