#176 ActiveTimerの動的表示
Let-s-Hack/goggl pull request #202
Opened 2020-02-15 03:15 UTC by KeisukeHomma

close #176

2020-02-15 04:43 UTC, usmysa reviewed
コメントの追加

2020-02-15 04:43 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +export default class ActiveTimer extends Mixins(TimeCounterMixin) {
ちなみに、Mixin以外の選択肢と、それぞれのメリデメは？

2020-02-15 04:43 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +  created() {
変数（local state、computed）→ 関数だから、こいつ後。
https://jp.vuejs.org/v2/style-guide/index.html#%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88-%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9-%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E9%A0%86%E5%BA%8F-%E6%8E%A8%E5%A5%A8

2020-02-15 04:43 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +  created() {
もう3~4ヶ月実装してるのと、一度似たようなコメントされてるんだから、こうゆう指摘がされないようにしてほしい
（要するにコードレビューしてたら、何も考えずに実装してるんだなって分かるってこと）

2020-02-15 04:43 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +  private timeoutId: number | null = null;
timeoutIdが一般的ならいいんだけど、パッと見だと、時間が経ったらタイムアウトのタイムアウトと勘違いした

2020-02-15 04:43 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +  private duration: number | null = null;
初期値はnullではなく、0ではダメなの？

2020-02-15 04:43 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +    this.timeoutId = setTimeout(() => this.start(startDatetime), delay);
setIntervalじゃなくて、setTimeoutの理由は何？

2020-02-15 04:43 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +    if (this.duration !== null && this.duration > maxDuration) return;
条件式多いの好きじゃないなぁー...
どうにかできないか...

2020-02-15 04:43 UTC, usmysa commented on src/store/modules/TimeRecorder.ts
> +    return (projectId: number): boolean => projectId !== this.noProjectId;
わざわざ変数に置くんじゃなくて、RecordManager.noProjectIdはダメなの？

2020-02-15 04:57 UTC, usmysa commented on src/store/modules/TimeRecorder.ts
> +    return (projectId: number): boolean => projectId !== this.noProjectId;
static対策か理解！

2020-02-15 06:19 UTC, KeisukeHomma reviewed
コメントを追加

2020-02-15 06:19 UTC, KeisukeHomma commented on src/components/molecules/ActiveTimer.vue
> +  created() {
すみません、、、

2020-02-15 06:19 UTC, KeisukeHomma commented on src/mixins/TimeCounterMixin.ts
> +    this.timeoutId = setTimeout(() => this.start(startDatetime), delay);
1秒間処理を遅延させる setTimeout より、一定間隔おきに実行する setInterval のほうが適しているね。
https://hakuhin.jp/js/timer.html

2020-02-15 06:19 UTC, KeisukeHomma commented on src/components/molecules/ActiveTimer.vue
> +export default class ActiveTimer extends Mixins(TimeCounterMixin) {
### 候補

**前提**
- ローカルステートを更新できる
    - durationSelector など、編集中の値の経過時間のカウントをする場面もある→ローカルステートを更新する


#### Mixinでかく

- メリット
    - 処理を共通化できる
    - ローカルステートを更新できる
- デメリット
    - 処理が暗黙的になり、コンポーネントのコードが読みづらくなる

#### 共通関数でかく

- メリット
    - 処理の一部を共通化できる
- デメリット
    - 再帰処理は、呼び出しているコンポーネント内で行う必要がある（処理の分散）

#### TimeRecorder モジュールにかく

- メリット
    - 処理を共通化できる
- デメリット
    - コンポーネントのローカルステートを更新できない→（対象外）


#### 結論

今回はローカルステートの更新をしたいので、Mixinで共通化することにした

2020-02-15 06:26 UTC, KeisukeHomma reviewed
コメントを追加

2020-02-15 06:26 UTC, KeisukeHomma commented on src/mixins/TimeCounterMixin.ts
> +  private passedSeconds: number = 0;
コンポーネントで定義している duration と名前がバッティングしそうなので `passedSeconds` に変更

2020-02-15 06:26 UTC, KeisukeHomma commented on src/mixins/TimeCounterMixin.ts
> +  public startTimer(startDatetime: string | null): void {
コンポーネント側で呼び出したときに `this.start` だとなんのことかわからないので、 `startTimer` とした

2020-02-16 03:38 UTC, usmysa reviewed
コメントの追加

2020-02-16 03:38 UTC, usmysa commented on src/store/modules/TimeRecorder.ts
> +  }
既に同じ関数があるはずなのに、なぜ同じ関数をつくるの!?

2020-02-16 03:38 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +export default class ActiveTimer extends Mixins(TimeCounterMixin) {
そもそも、必ずしもローカルステートでないといけないのか理由が分からない
別に、timerRecordのstateを1秒ごとに更新して取得するっていう方法もあるのでは？

2020-02-16 03:38 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +  public startTimer(startDatetime: string | null): void {
クラスと一緒に考えた場合、`TimeCounter.startTimer`と`TimeCounter.stopTimer`ってよく分からんな...
（クラス名が微妙）

2020-02-16 03:38 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +      || this.passedSeconds > maxSeconds
この処理がなかった場合って、どれだけ弊害なの？

2020-02-16 03:38 UTC, usmysa commented on src/mixins/TimeCounterMixin.ts
> +    this.intervalId = setTimeout(() => this.startTimer(startDatetime), delay);
これ、`setInterval`の間違い？

2020-02-16 03:38 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +export default class ActiveTimer extends Mixins(TimeCounterMixin) {
utilsの中にclassを使って、単純に経過時間を取得するのもありでは？

2020-02-17 12:54 UTC, KeisukeHomma commented on src/store/modules/TimeRecorder.ts
> +  }
`TimeRecorder` ：現在進行中のタイマー
`RecordManager` ：過去のタイマーの記録

だと思ってたから、別々に作らないとダメなのかと

2020-02-18 04:18 UTC, usmysa reviewed
コメントの追加

2020-02-18 04:18 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +  private timeCounter: TimeCounter | null = null;
わざわざnullを設定するんじゃなくて、ここでインスタンス化してはダメなの？

2020-02-18 04:18 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +    delete this.timeCounter;
ちなみに、ここでdeleteしてる理由ってなんなの？

2020-02-18 04:18 UTC, usmysa commented on src/store/modules/TimeRecorder.ts
> +  }
であれば、他の案も考えればいいのでは??
別に、ProjectManagerに置いて共通化するという案もあると思うが...

2020-02-18 04:18 UTC, usmysa commented on src/utils/timeCounter.ts
> +  public duration: number = 0;
publicだと他の箇所でも値を変更可能だから、private変数にしてgetter関数を作った方が良いかと

2020-02-18 04:18 UTC, usmysa commented on src/utils/timeCounter.ts
> +  private delay: number = 1000;
readonlyでは？
っていうのと、class外でconstに置くのはダメ？
（classのプロパティで持つのと、constで持つ違いとかわからないけど）

2020-02-18 04:18 UTC, usmysa commented on src/utils/timeCounter.ts
> +    this.startDatetime = startDatetime;
元（ActiveTimer）のstartDatetimeってどうなってるんだっけ？
絶対、初期値が今の時刻なら微妙だけど、
引数があれば、その日付をstartDatetimeに設定
引数がなければ、今の時刻をstartDatetimeに設定するとスマートかなと思った

2020-02-18 04:18 UTC, usmysa commented on src/utils/timeCounter.ts
> +      if (this.startDatetime === null) return;
この処理、setIntervalの中でやる必要ある？
constructorでstartDatetimeがnullを指定される以外ありえないと思う
（startDatetimeを設定する場所がそこしかないため）

2020-02-18 04:18 UTC, usmysa commented on src/utils/timeCounter.ts
> +  private delay: number = 1000;
処理とか意味合い的にdelayなのは確かに正しいけど、1秒以外になることはないから、`ONE_MILLISECOND`的なのではダメ？
（delayと抽象的に置くということは、1秒以外もありえるということ）

2020-02-19 15:11 UTC, KeisukeHomma reviewed
コメントを追加

2020-02-19 15:11 UTC, KeisukeHomma commented on src/components/molecules/ActiveTimer.vue
> +    delete this.timeCounter;
タイマーが止まってインスタンスが不要になるから、消すために delete している

2020-02-19 15:11 UTC, KeisukeHomma commented on src/utils/timeCounter.ts
> +    this.startDatetime = startDatetime;
TimerCreatorを開いた時点での日時が入るという感じ。
だから、ActiveTimer では常に今の時刻が入るというわけではない

2020-02-20 13:00 UTC, KeisukeHomma commented on src/store/modules/ProjectManager.ts
> +  }
ReportManagerのは影響範囲が大きいので他PRで対応

2020-02-21 10:52 UTC, usmysa requested changes
コメントの追加

2020-02-21 10:52 UTC, usmysa commented on src/store/modules/ProjectManager.ts
> +  }
RecordManager.hasProjectは、レコードがプロジェクトを持っているか/紐付いているかという意味で通るけど、ProjectManager.hasProjectって意味分からなくない？
それこそ、existsみたいなそのプロジェクトが存在するのかみたいに聞こえる

2020-02-21 10:52 UTC, usmysa commented on src/utils/timeCounter.ts
> +    this.startDatetime = startDatetime;
早期リターンしなくても、純粋に三項演算子を使えばいいのでは？

2020-02-23 12:26 UTC, usmysa requested changes
コメントの追加

2020-02-23 12:26 UTC, usmysa commented on src/store/modules/ProjectManager.ts
> +  }
いやいや…
やってる処理の内容と関数名一致してないでしょ…
そもそもコメントされてる内容を理解してないから、文章をちゃんと読もうか

2020-02-23 12:26 UTC, usmysa commented on src/utils/timeCounter.ts
> +    const calcDuration: Function = (): void => {
単なる質問だけど、関数をクラスメソッドではなく、変数においてる理由はなぜ？

2020-02-23 12:26 UTC, usmysa commented on src/utils/timeCounter.ts
> +    if (this.startDatetime === null) return;
start関数を呼び出す時に、startDatetimeがnullのことなんて、ありえなくね？

2020-02-23 12:45 UTC, KeisukeHomma reviewed
コメント追加

2020-02-23 12:45 UTC, KeisukeHomma commented on src/store/modules/ProjectManager.ts
> +  }
すいません。

2020-02-23 12:45 UTC, KeisukeHomma commented on src/utils/timeCounter.ts
> +    const calcDuration: Function = (): void => {
外に出した場合、 getDuration と calcDuration が並列にあったら分かりにくいかな、と思って

2020-02-27 12:15 UTC, usmysa reviewed
コメントの追加

2020-02-27 12:15 UTC, usmysa commented on src/components/molecules/ActiveTimer.vue
> +      <span class="ActiveTimer_Title">{{ timer.title }}</span>
timer.titleって意味分からなくない？

2020-02-27 12:15 UTC, usmysa commented on src/utils/timeCounter.ts
> +    calcDuration();
ここの1回がなかったら、何が生じる？

2020-02-27 12:15 UTC, usmysa commented on src/utils/timeCounter.ts
> +    const calcDuration: Function = (): void => {
関数名の問題では!?
classのプロパティを変更する関数がclassメソッドじゃないのも気持ち悪い

2020-03-13 11:46 UTC, KeisukeHomma reviewed
コメント追加

2020-03-13 11:46 UTC, KeisukeHomma commented on src/utils/timeCounter.ts
> +    calcDuration();
最初の１秒間、durationの計算がされなくなっちゃう

2020-03-13 12:00 UTC, merged