#9 Atoms作成、読み込み
Let-s-Hack/goggl pull request #26
Opened 2019-11-28 15:41 UTC by KeisukeHomma

close #9 

atoms/ApplyButton.vue
atoms/BaseCard.vue
atoms/BottomSheet.vue
atoms/CancelButton.vue
atoms/LoadingBar.vue

2019-11-29 14:58 UTC, usmysa reviewed
単なる質問

2019-11-29 14:58 UTC, usmysa commented on src/components/atoms/ApplyButton.vue
> +    </p>
【感想】
若干、細かいけどボタンのタイトルって一般的に言うかなと思った
こっちがTextで上のほうが、HelperTextとかになるのかなと思った

2019-11-29 14:58 UTC, usmysa commented on src/components/atoms/ApplyButton.vue
> +  background: #efefef;
今回のコーディングでスタイルで決まった通り、大文字対応

2019-11-29 14:58 UTC, usmysa commented on src/components/atoms/ApplyButton.vue
> +.ApplyButton {
ここもめちゃくちゃ細かいけど、インデントそのままにしたほうがいいのか、一段ずらしたほうがいいのか

2019-11-29 14:58 UTC, usmysa commented on src/components/atoms/BackgroundOverlay.vue
> +  background: rgba($color: #D4D4D9, $alpha: 0.87);
書き方の統一問題

2019-11-29 14:58 UTC, usmysa commented on src/components/atoms/CancelButton.vue
>    <div class="CancelButton">
buttonタグではない？

2019-11-29 15:06 UTC, KeisukeHomma commented on src/components/atoms/ApplyButton.vue
> +    </p>
Titleは確かに違和感がある。
TextとSubTextとかにしてみよう

2019-11-29 15:06 UTC, KeisukeHomma commented on src/components/atoms/ApplyButton.vue
> +.ApplyButton {
インデントしないでいきましょう

2019-11-30 04:17 UTC, KeisukeHomma commented
Record, RecordListItemを作成

2019-12-01 06:55 UTC, usmysa requested changes
確認した

2019-12-01 06:55 UTC, usmysa commented on src/components/atoms/BackgroundOverlay.vue
> +  background: rgba($color: #D4D4D9, $alpha: 0.87);
対応されてないー？

2019-12-01 06:55 UTC, usmysa commented on src/components/atoms/RecordListItem.vue
> +export default class RecordListItemListItem extends Vue {
名前あってる？
コピペミス？

2019-12-01 06:55 UTC, usmysa commented on src/components/atoms/Record.vue
> +      <h3 class="Record_Title">タイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトル</h3>
h3の理由って何？
スクショでいう「Yesterday」「Thu, 21 Nov」がh2だとしたら、レコードのタイトルがh3ってこと？
だとしたら、RecordListItemとRecordのタイトルが両方h3なのは、構造的におかしい気がする
（この理論でいくと、Recordはh4になるべき）

2019-12-01 07:04 UTC, usmysa commented on src/components/atoms/RecordListItem.vue
> +      <h3 class="RecordListItem_Title">タイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトル</h3>
h3の理由って何？
スクショでいう「Yesterday」「Thu, 21 Nov」がh2だとしたら、レコードのタイトルがh3ってこと？
だとしたら、RecordListItemとRecordのタイトルが両方h3なのは、構造的におかしい気がする
（この理論でいくと、RecordListItemはh4になるべき）

2019-12-01 08:46 UTC, usmysa commented on src/components/atoms/Record.vue
> +      border-color: inherit;
ショートハンドプロパティを使った方がファイル容量が少なくなって、パフォーマンスが改善されるって書いてる
https://murashun.jp/blog/20180817-01.html#chapter-6

2019-12-01 12:03 UTC, KeisukeHomma commented on src/components/atoms/BackgroundOverlay.vue
> +  background: rgba($color: #D4D4D9, $alpha: 0.87);
失礼しました

2019-12-01 12:04 UTC, KeisukeHomma commented on src/components/atoms/RecordListItem.vue
> +export default class RecordListItemListItem extends Vue {
コピペみすでした

2019-12-01 12:05 UTC, KeisukeHomma commented on src/components/atoms/RecordListItem.vue
> +      <h3 class="RecordListItem_Title">タイトルタイトルタイトルタイトルタイトルタイトルタイトルタイトル</h3>
確かにそうだね、変更しました

2019-12-01 12:17 UTC, KeisukeHomma commented on src/components/atoms/Record.vue
> +      border-color: inherit;
ここはコメント書いておくべきだったね。

Projectの色をstyle属性で指定しているんだけど、style属性では擬似要素に直接スタイルを定義できない。
そこで、親（ `.Record_Project` ）の `border-color` に子（ `.Record_Project::before` ）で使いたい色を指定して、子で親の `border-color` を継承する形で実装している。
ショートハンドプロパティを指定してしまうと `border-color` に `inherit` を指定できないので、このように記述している。

2019-12-01 12:28 UTC, merged