#12 円グラフを作成
Let-s-Hack/goggl pull request #62
Opened 2019-12-22 09:02 UTC by KeisukeHomma

2019-12-23 16:14 UTC, usmysa requested changes
大学で英語をやってなかったのが伝わった瞬間

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      (lastAngle - 90) * Math.PI / 180,
変数名が違う気がする
firstAngle => startAngle
lastAngle => endAngle
https://developer.mozilla.org/ja/docs/Web/API/CanvasRenderingContext2D/arc

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  textRadius: number = this.radius - 8;
centerPositionをcanvasSizeの1/4にするとかって完全にロジックだから、dataで宣言するんじゃなくて、関数化すべきかなとは思う

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  pieChartMargin: number = 54 * 2;
108じゃない理由って何？

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  canvasSize: number = (window.innerWidth - this.pieChartMargin) * 2;
canvasとpieChartって表記ゆれしてない？

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  piePieces: any = [
piecesっていう表現は英語的に違うかな
調べた感じ、groupかな

> group on the pie

https://www.d3-graph-gallery.com/graph/pie_basic.html

> Group
> EUL
> PES
> ...

https://en.wikipedia.org/wiki/Pie_chart

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      if (angle - beforeAngle <= 36) return;
コメントと内容が一致してる？
36がマジックナンバー

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  drawPieText(angle: number, projectName: string, percentage: number) {
pieTextも英語的に間違ってるかな
dataLabelかな
https://support.office.com/en-us/article/add-or-remove-data-labels-in-a-chart-884bf2f1-2e29-454e-8b42-f467c9f4eb2d

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    const radian = (angle - 90) * Math.PI / 180;
> (x - 90) * Math.PI / 180

何回も使ってる + 何を算出してるのか分かりにくいので関数化

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      // 角度が180°より小さい場合
> 角度が180°より小さい場合

if文を見ればわかるから、コメントとして意味ないかな...

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      this.ctx!.fillText(`${percentage}%`, 0, 0);
ここらへん、若干パラメータの値が違うけど、やってる処理ほぼ同じだよね
冗長だから関数化して

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  static percentageToAngle(percentage: number) {
・static関数にした理由はなにか
・関数の返り値の型がない

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  drawAllPieText() {
個人的には、void型であればvoidを明示的に書くべきだと思う

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    // transformをリセットして
して何？w

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      <li v-for="(pie, index) in piePieces" :key="index" class="ReportsPieChart_Category">
> pie, index

細かいけど、pieじゃなくてpieceだよね

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +           {{pie.projectName}}
スタイルガイドにはないけど、どれを見てもVueのマスタッシュ記法は半角が必須だと思う...

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    <div ref="PieChartContainer" class="ReportsPieChart_Figre">
> Figre

Figure

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    <ul class="ReportsPieChart_CategoryList">
CategoryじゃなくてProjectじゃないかね

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +        <p class="ReportsPieChart_Time">{{pie.duration}}</p>
> pie.duration

使い方間違ってない？
durationって期間って意味だよ

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    <div ref="PieChartContainer" class="ReportsPieChart_Figre">
> PieChartContainer

使ってないよね

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +        class="ReportsPieChart_Canvas"
個人的に、クラス名って何を表しているかを表現するもので、手段（= canvas）がクラス名なのは違和感を感じる...

2019-12-23 16:14 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  drawAllPieText() {
処理を見た感じ、drawAllPiePiecesとまとめられる気がするんだけど、ダメ？

2019-12-27 15:43 UTC, KeisukeHomma reviewed
コメント

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +        class="ReportsPieChart_Canvas"
FigureInnerに変更

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +    <ul class="ReportsPieChart_CategoryList">
たしかに
Projectに変更

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +        <p class="ReportsPieChart_Time">{{pie.duration}}</p>
ああー、すまん

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +  pieChartMargin: number = 54 * 2;
よく時間とかの変数で `lifeTime = 2 * 60` とかやるのを見るから、
どういう計算をしてその数字になったのか明示的になっていいのかと思い。

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +  canvasSize: number = (window.innerWidth - this.pieChartMargin) * 2;
すまん

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +  drawPieText(angle: number, projectName: string, percentage: number) {
検索力つけます

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +  static percentageToAngle(percentage: number) {
> ESlintのclass-methods-use-thisルールを有効にしている場合、
thisを使用しないメソッドに関しては静的メソッドを定義する必要がありまして、
static MyMethod()としていないと、次のようなエラーになります。

> MyClass.callStaticMethod() と記述することで、
補助メソッド的に他のメソッドで呼び出すことが可能です。


https://qiita.com/pokkur/items/1619fe726f0cb7f45874

2019-12-27 15:43 UTC, KeisukeHomma commented on src/components/organisms/ReportsPieChart.vue
> +  drawAllPieText() {
長くなるけど許容範囲なのでまとめた

2019-12-27 17:03 UTC, usmysa reviewed
コメントの追加

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +        class="ReportsPieChart_FigureInner"
canvasがInner!?

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +        <p class="ReportsPieChart_Percent">{{piece.percent}}%</p>
ここ以降のマスタッシュ記法が対応されていない

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  pieceGroup: any = [
piece部分のことをgroupっていう

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      time: '12:33:11',
個人的には、アクセスしにくくなるけど、フラットなデータ構造が微妙だなぁーって感じた
```
{
  project: {
    name: 'プロジェクトX',
    color: '#3F46E3',
  },
  time: {
    percent: 35,
    sum: '12:33:11',
  }
}
```

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +    let beforeAngle = 0;
変数名が前置詞を含むのはおかしい
形容詞のprevious, current, nextが一般的

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +  static percentToDegree(percent: number): number {
結局、thisにするって話じゃなかったっけ？

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      if (angle - beforeAngle <= ReportsPieChart.percentToDegree(10)) return;
angle - beforeAngleを変数に置く
（角度から前の角度を引くっていう変数名もおかしい）

2019-12-27 17:03 UTC, usmysa commented on src/components/organisms/ReportsPieChart.vue
> +      if (angle - beforeAngle <= ReportsPieChart.percentToDegree(10)) return;
調整用の-16とかの値はいいけど、ロジックに使ってる10はマジックナンバーだから、定数に置く

2019-12-27 18:34 UTC, merged